# https://github.com/commercialhaskell/stack/blob/master/doc/travis_ci.md

# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  # Build dependencies
  - stack --no-terminal --install-ghc build --only-dependencies

script:
  # Build the package, its tests, and its docs and run the tests
  - stack --no-terminal build
  # - stack --no-terminal test
  # - stack --no-terminal haddock

notifications:
  slack:
    secure: fzDEy4SjCatJCbdjqSLTpOb1bEi7vc2zeEp1Ws144Um/cCfMCWMfW0sjRO1v4T2mdhnUxv3qyEOX/RSO5SzCUcz0P0qN+DTtj+Uj3CXT1xQEtYto/48utC2hXiYFzrTf9mawilvrnhzrMfZjfSi1/TAG5l5PM4zkLhCDLjUfitYOFx19I3ecna2GdBnn3XcEjO5Tm+VHrg2rT17hx1kEyWD/z1o7X11v6b8z9u7ivDcakkRjW7+HxDw2ylbgOsfLwZoDqdMaSmse59Fkk9PlUX460mN+Fm0QPM2UsZ5HNvBzKqL4UWUVKD2XN9Q7q98AuCKV30xgh1r5102CWhEBUIuIvm5ZyWoGdC5+Cp5DiFnBxl/d2+LzXeKY3HENEcl0RFwXYTcdpC1FSawsG1ynEyg1+WUqjUyHX3LlDS0ML6cWGfkjITiOIJ+KAp47pQSCDLHHvIxPEIDm8R82CwdK/GFzVn80+yMffVQt05LAvyE7Dw5sJ6u27TTSwAKFXw+NZ5A9k+4hMKz+niYPo3Awp1Ut6AA3bUEl6DzBajz74jXfE1t8W4IRmQt4ikafucoo1EOiuUoD+VVE/O6kvZpjZ3TND4j+/QuNw/4jTqLoIYlS6hdvBSGjJGuidovfAL55cJAFtv//kIw8UOliNLyCZ0NGp9D0ZI++hsc/xPNVzN4=

