name: mental
version: '0.1.0.0'
category: Development
author: Romain Ruetschi
maintainer: romain.ruetschi@gmail.com
copyright: 2016 Romain Ruetschi
license: BSD3
github: romac/mental
extra-source-files:
  - README.md

ghc-options:
  - -Wall
  # - -fno-warn-warnings-deprecations
  # - -fno-warn-unused-imports
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings

executables:
  mentalist:
    main: Main.hs
    source-dirs: mentalist
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - free
      - haskeline
      - megaparsec
      - mental
      - protolude
      - text
      - wl-pprint-text

library:
  source-dirs: src
  dependencies:
    - base >=4.7 && <5
    - comonad
    - containers
    - deriving-compat
    - free
    - haskeline
    - megaparsec
    - mtl
    - protolude
    - recursion-schemes
    - semigroups
    - text
    - transformers
    - wl-pprint-text

tests:
  mental-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - mental
      - protolude

