name: mental
version: '0.1.0.0'
category: Development
author: Romain Ruetschi
maintainer: romain.ruetschi@gmail.com
copyright: 2016 Romain Ruetschi
license: BSD3
github: romac/mental
extra-source-files:
  - README.md

ghc-options: -Wall -Werror
default-extensions: NoImplicitPrelude

executables:
  mentalist:
    main: Main.hs
    source-dirs: mentalist
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - mental
      - megaparsec
      - protolude
      - readline
      - text
      - wl-pprint-text

library:
  source-dirs: src
  dependencies:
    - base >=4.7 && <5
    - containers
    - freer
    - megaparsec
    - mtl
    - protolude
    - readline
    - semigroups
    - text
    - transformers
    - unbound-generics
    - wl-pprint-text

tests:
  mental-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - protolude
      - mental

