
resolver: lts-7.19

packages:
  - '.'

extra-deps: []

flags: {}

extra-package-dbs: []

extra-include-dirs:
  - /usr/local/Cellar/readline/7.0.1/include

extra-lib-dirs:
  - /usr/local/Cellar/readline/7.0.1/lib
